#!/bin/sh

. /kasane/tetorc/tlib/rc.lib

mkdir -pm 0755 /run/tetorc /run/lvm /run/user /run/lock /run/log \
    /dev/pts /dev/shm

mnt /dev/pts devpts devptsfs mode=0620,gid=5,nosuid,noexec
mnt /dev/shm tmpfs shmfs mode=1777,nosuid,nodev

[ -h /dev/fd     ] || ln -sf /proc/self/fd /dev/fd
[ -h /dev/stdin  ] || ln -sf fd/0 /dev/stdin
[ -h /dev/stdout ] || ln -sf fd/1 /dev/stdout
[ -h /dev/stderr ] || ln -sf fd/2 /dev/stderr

mount -o remount,ro /
fsck -ATat noopts=_netdev
[ $? -gt 1 ] && log "filesystem check failed"
mount -o remount,rw /
swapon -a
