#!/bin/sh

. /kasane/tetorc/tlib/rc.lib

setup_tty(){
    for index in 1 2 3 4 5 6; do
        # Launch getty once per TTY in the background
        agetty 38400 "tty${index}" linux &
    done

    # No need to wait indefinitely; just return control to init
}

setup_tty
